### ISSUE TITLE
`WP_HTML_Tag_Processor::next_tag()` should accept `string`

### ISSUE THREAD

**Issue by dlh01** [php-stubs/wordpress-stubs#182]
`WP_HTML_Tag_Processor::next_tag()` allows `array|string|null`, but the PHPStan parameter in the stubs is limited to:

```
         * @phpstan-param null|array{
         *   tag_name?: string|null,
         *   match_offset?: int|null,
         *   class_name?: string|null,
         *   tag_closers?: string|null,
         * } $query
```

The result is that developers have to pass `[ 'tag_name' => 'foo' ]` to satisfy PHPStan instead of just `foo`.

**Comment by szepeviktor** [comment]
It is good to be explicit, isn't it?

**Comment by johnbillion** [comment]
This is intentional due to the many functions in WordPress which accept either an array or a query variable string (eg. `func( 'foo=bar' )`). The visitor in this library removes the string type for increased strictness.

https://github.com/php-stubs/wordpress-stubs/blob/9e46871d5af584ae9f170ba06bcf2c2ebcd55418/src/Visitor.php#L523-L525

**Comment by szepeviktor** [comment]
> for increased strictness.

**Comment by dlh01** [comment]
For this particular method on this particular class, I haven't yet found it helpful to be explicit, but I can accept that it's being done intentionally. Thanks!
