### ISSUE TITLE
Improve types for `WP_REST_Request`

### ISSUE THREAD

**Issue by swissspidy** [php-stubs/wordpress-stubs#65]
Right now in my project I have a bunch of REST controllers that take some request params and then do something with them. With `WP_REST_Request` implementing `ArrayAccess` and things like `$request['foo']` being `mixed`, I need to use inline `@var` tags to tell PHPStan what type I am expecting.

Example:

```php
/**
 * @param WP_REST_Request $request Full details about the request.
 * @return WP_REST_Response|WP_Error Response object on success, WP_Error object on failure.
 */
public function create_item( $request ) {
	/**
	 * Parent post.
	 *
	 * @var int $parent_post
	 */
	$parent_post = ! empty( $request['post'] ) ? $request['post'] : null;

	/**
	 * Field to order by.
	 *
	 * @var string $orderby
	 */
	$orderby = ! empty( $request['orderby'] ) ? $request['orderby'] : 'date';

	// ...
}
```

That works fine so far.

However, [with PHPStan 1.10 there is an effort underway](https://phpstan.org/blog/phpstan-1-10-comes-with-lie-detector) to get rid of these inline `@var` tags. The suggestion is to fix the wrong 3P docblocks instead of having to provide these inline tags myself.

So how can we fix the `WP_REST_Request` docblocks? I am asking this here because this can be done at the stub level and there's no need for a custom PHPStan extension.

According to [this post](https://phpstan.org/blog/generics-in-php-using-phpdocs) we should be able to add something like this to `WP_REST_Request` in the stubs:

```php
/**
 * @template T
 * @implements Collection<T>
 */
```

Note: the same goes for `WP_Theme`, which also implements `ArrayAccess`

**Comment by johnbillion** [comment]
There's [a NodeVisitor](https://github.com/php-stubs/wordpress-stubs/blob/db1e23a29bd0acf7c2776e45ac3c5f12ce4b99d7/visitor.php) which reads information from [functionMap.php](https://github.com/php-stubs/wordpress-stubs/blob/db1e23a29bd0acf7c2776e45ac3c5f12ce4b99d7/functionMap.php) in order to add extra tags to those symbols. [It doesn't support doing that at the class level](https://github.com/php-stubs/wordpress-stubs/blob/db1e23a29bd0acf7c2776e45ac3c5f12ce4b99d7/visitor.php#L265), but it could be modified to do that.

**Comment by szepeviktor** [comment]
This is so scientific! 👨🏻‍🔬

**Comment by swissspidy** [comment]
Having troubles running the generator locally on PHP 8, but here's a WIP PR: #66
