### ISSUE TITLE
Ondřej says: It doesn't make sense to combine void with something else in a union type.

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#98]
We have a few of `string|void`-s:
https://github.com/php-stubs/wordpress-stubs/blob/1d136936e4124a52632e0f5f9470165c9fd106b7/functionMap.php#L115-L119

https://github.com/phpstan/phpstan/issues/9288

**Comment by szepeviktor** [comment]
@johnbillion Should we remove those or delete WordPress from the Internet?

**Comment by szepeviktor** [comment]
These _return or echo_ functions violate the followings.

- 1 function should do 1 thing
    ```php
    function get_this($this) {
        return $this;
    }
    function print_this($this) {
        echo get_this($this);
    }
    ````
- never use boolean parameters

**Comment by johnbillion** [comment]
Unfortunately `string|void` is accurate for those functions. As Ian pointed out this was also brought up in https://github.com/szepeviktor/phpstan-wordpress/issues/176, I think in WordPress core we can switch to returning `null` instead of `void` without a backwards compatibility concern. Just need someone to open a PR to core (I'm not planning on it myself).

**Comment by szepeviktor** [comment]
This is my Numero Uno function missing from WordPress core.
```php
/**
 * @param mixed $condition
 */
function ifPrint($condition, string $string): void
{
    if (!$condition) {
        return;
    }

    // phpcs:ignore Squiz.PHP.DiscouragedFunctions.Discouraged
    print $string;
}
```
